version: "3"

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'docker_db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    expose:
      - "3306"
  app:
    build:
      context: .
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
      

